#!/bin/bash

USAGE="$(basename $0) project revision(s) destination_branch [source_branch]"

fullSource=trunk
shortSource=trunk
project=${1}
revision=${2}
destination=${3}
if [ -n "${4}" ]; then
    shortSource=${4}
    fullSource=branches/${4}
fi

case ${project} in
    ecom)
        cd /Volumes/codebase/www/
        ;;
    webdev)
        cd /Volumes/codebase/www/da.store
        ;;
    *)
        echo "$USAGE"
        exit 1
        ;;
esac

echo -e "Update trunk and branches\c"
 
svnu

echo "Beginning merge from ${shortSource} to ${destination}"
cd ${destination}
svn merge -c ${revision}  https://subversion.deliveryagent.com/svn/${project}/${fullSource} .
echo "Press Enter to continue or Ctrl-C to stop"
read a
svn ci -m "merging revision ${revision} from ${shortSource} to ${destination} branch"
