#!/bin/bash

branchname=`git rev-parse --abbrev-ref HEAD | cut -d '/' -f2 `
commitMsgFile=$1
commitMode=$2
changedFiles=`git status --porcelain`

# $2 is the commit mode
# if $2 == 'commit'  => user used `git commit`
# if $2 == 'message' => user used `git commit -m '...'`

existingMsg=`cat $commitMsgFile`
if [ "$commitMode" = "message" ]; then

	echo -n "[$branchname] - $existingMsg" > $commitMsgFile
	echo -e "n\n\nModified Files\n$changedFiles" >> $commitMsgFile


else

	firstline=`head -n1 $commitMsgFile`

 	#We check the fist line of the commit message file.
	#If it's an empty string then user didn't use `git commit --amend` so we can fill the commit msg file
  	if [ -z "$firstline" ]; then
    	echo  "[$branchname] #Commit message here" >> $commitMsgFile
    	echo  -e "\n\n\nModified Files\n$changedFiles" >> $commitMsgFile
  	fi

fi