#!/bin/bash

versions="itv_dev itv_qa itv_demo"
for i in $versions; do
    for j in /Volumes/codebase/www /Volumes/codebase/www/da.store; do
        cd ${j}/${i}
        header ${PWD}
    case $1 in
            -v)
                svn log -v -v --limit=${2:-5} ${PWD}
                ;;
            -l)
                svn log --limit=${2:-5} ${PWD}
                ;;
            -p)
                svn propget svn:mergeinfo ${PWD}
                ;;
            -s)
                # svn st ${i}
                whathaveichanged ${PWD}
                ;;
            *)
                svn update ${PWD}
                ;;
        esac
    done
done