#!/bin/bash

USAGE="$(basename $0) project [tags|branches|trunk] [branch name | tag name]"

project=${1}
source1=${2}
sourceName=${3}
base=https://subversion.deliveryagent.com/svn

case ${source1} in
	trunk|TRUNK)
		svn info ${base}/${project}/${source1} | grep "Last Changed Rev:"
		;;
	tags|TAGS|branches|BRANCHES)
		svn info ${base}/${project}/${source1}/${sourceName} | grep "Last Changed Rev:"
		;;
	*)
		echo "$USAGE"
		exit 1
esac
