#!/bin/bash
USAGE="$(basename $0) project"

defaultSource=trunk
from=${1}
base=/Volumes/codebase/www/da.store/foodnetwork

if [ -n "${1}" ]; then
    from=${1}
fi

echo "Updating local branches"
svnu 


cd ${base}/htdocs
svn merge ^/trunk/htdocs/foodnetwork foodnetwork
svn merge ^/trunk/htdocs/genericplus genericplus

cd ${base}/templates
svn merge ^/trunk/templates/store_genericplus store_genericplus
svn merge ^/trunk/templates/store_foodnetwork store_foodnetwork

svn diff --summarize

echo "Do you wish to merge release_fortrust into foodnetwork? Press Enter to continue without release_fortrust update, or Y to update"
read a

case ${a} in
    y*|Y*)
        cd ${base}
        svn merge ^/branches/release_fortrust .
        ;;
    *)
        echo "Continuing"
        ;;

esac

echo "Do you wish to continue with merge and commit? Enter to continue, n to stop, and r to stop and revert"
read b

case ${b} in
    n|N)
       echo "Ending, changes are not committed but also not reverted. To revert, please use r option or [svn revert -R .]"
	   exit 1
        ;;
    r|R)
        cd ${base}
        svn revert -R .
        echo "Updates have been reverted"
        ;;
    *)
        cd ${base}
       	svn ci
        ;;
esac

echo "Update Complete."
